import type { IOrgCompany } from "./hm3int";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const spdata:any[] = [
    {
        "Id": 1,
        "Title": "STADT DUISBURG",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://www.google.de/",
            "Url": "https://www.google.de/"
        },
        "Logo": '/vite.svg',
        "Logo_x0020_Large": undefined,

    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "a7410199-0271-4e68-8708-a130eb1c1e96",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(2)",
        "Id": 2,
        "Title": "RheinEnergie AG",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 2
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "cae92cfa-c76b-47a5-b4d5-511ce50f96a5",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(3)",
        "Id": 3,
        "Title": "Stadt Dinslaken",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 3
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "be7df4c5-0093-4a70-b86c-41cc79d83bfb",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(4)",
        "Id": 4,
        "Title": "Kreis Wesel",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 4
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "87731444-8aa0-4bd3-afb1-833a1acb4943",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(5)",
        "Id": 5,
        "Title": "Stadtwerke Duisburg AG",
        "City": "Duisburg",
        "Value": "Grundkapital 85.000.000,00 DM",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "1140",
        "StNr": "DE 811271592",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/sdag",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/sdag"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 5
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "5b1415f1-fb7d-43ff-9a38-fc0fb4dd7e23",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(6)",
        "Id": 6,
        "Title": "energieGUT GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 850.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "24115",
        "StNr": "DE 812805240",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/energiegut",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/energiegut"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 6
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "64bf7cee-2644-41f4-8279-1c89abf768b8",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(7)",
        "Id": 7,
        "Title": "Stadtwerke Duisburg Energiehandel GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 2.000.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "8285",
        "StNr": "DE 813164153",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/swdu-eh",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/swdu-eh"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 7
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "2aaebe5f-c0db-4024-9ed2-0c4e7510db82",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(8)",
        "Id": 8,
        "Title": "Netze Duisburg GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 20.000.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "19130",
        "StNr": "DE 252113622",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/netzeduisburg",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/netzeduisburg"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 8
    },
    {
        
        "Id": 9,
        "Title": "ThermoPlus WärmeDirektService GmbH Duisburg",
        "City": "Duisburg",
        "Value": "Stammkapital 1.200.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "7224",
        "StNr": "DE 182536034",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/thermoplus",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/thermoplus"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 9
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "65ac9264-297b-4c93-9157-d7f36dc2e97c",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(10)",
        "Id": 10,
        "Title": "RheinEnergie-Stadtwerke Duisburg Windpark Verwaltungs GmbH ",
        "City": "Duisburg",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "31869",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/renergie",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/renergie"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 10
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "0a96428d-fc64-4393-bb09-4e35abcf1343",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(11)",
        "Id": 11,
        "Title": "GREEN GECCO Beteiligungsgesellschaft-Verwaltungs GmbH",
        "City": "Troisdorf",
        "Value": "Stammkapital 30.420.00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "10833",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/greengeccombh",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/greengeccombh"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 11
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "6ad345c4-f2c4-454d-8fc5-ba3ec7069bf7",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(12)",
        "Id": 12,
        "Title": "GREEN GECCO Beteiligungsgesellschaft mbH & Co. KG",
        "City": "Troisdorf",
        "Value": "Kommanditkapital 528.334.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 5249",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/greengecco",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/greengecco"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 12
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "329cce83-f3cb-4f5a-99fc-d6b926127d80",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(13)",
        "Id": 13,
        "Title": "Fernwärme Duisburg GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 4.000.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "24785",
        "StNr": "DE811271592",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fernwarmed",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fernwarmed"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 13
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "115492cc-9759-47af-b36b-5e7172ac8f3c",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(14)",
        "Id": 14,
        "Title": "Fernwärmeverbund Niederrhein Duisburg / Dinslaken Verwaltungsgesellschaft mbH",
        "City": "Dinslaken",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "13943",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fnddv",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fnddv"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 14
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "0205ea3f-d266-4e2a-a771-3d0b650522d6",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(15)",
        "Id": 15,
        "Title": "Fernwärmeverbund Niederrhein Duisburg/Dinslaken GmbH & Co. KG",
        "City": "Dinslaken",
        "Value": "Kommanditkapital 4.000.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 8304",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fvn",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fvn"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 15
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "4e67a67b-57a8-4c28-a3f0-61873295764f",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(16)",
        "Id": 16,
        "Title": "Wasserbeschaffung Niederrhein Westfalen GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 500.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "24676",
        "StNr": "DE262498608",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wbdu",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wbdu"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 16
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "51156a50-017b-4a16-a1b6-9d06561f1b66",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(17)",
        "Id": 17,
        "Title": "Wasserlabor Niederrhein GmbH",
        "City": "Mönchengladbach",
        "Value": "Stammkapital 200.000,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "7272",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wln",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wln"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 17
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "117e6e40-47f5-4a2f-8871-62f2c87421f1",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(18)",
        "Id": 18,
        "Title": "KSBG Kommunale Verwaltungsgesellschaft GmbH",
        "City": "Essen",
        "Value": "Stammkapital 100.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "22675",
        "StNr": "112 5767 1567",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/ksbgkommbh",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/ksbgkommbh"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 18
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "4aa1f0e1-54ec-4f47-a800-e8893ea887f5",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(19)",
        "Id": 19,
        "Title": "KSBG Kommunale Beteiligungsgesellschaft GmbH & Co. KG",
        "City": "Essen",
        "Value": "Kommanditkapital 1.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 9583",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/ksbgkommco",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/ksbgkommco"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 19
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "2f35ccd8-a461-4e07-b1bd-2f3a897bb310",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(20)",
        "Id": 20,
        "Title": "STEAG GmbH",
        "City": "Essen",
        "Value": "Stammkapital 128.000.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "19649",
        "StNr": "DE119821534",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/steag",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/steag"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 20
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "2f72bcdf-2607-446c-abde-31bfa822ecec",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(21)",
        "Id": 21,
        "Title": "Wasserverbund Niederrhein GmbH",
        "City": "Moers",
        "Value": "Stammkapital 2.310.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "15067",
        "StNr": "DE120343240",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wvn",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/wvn"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 21
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1246086e-8eba-4dfa-b89b-ecd422501709",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(22)",
        "Id": 22,
        "Title": "Fernwärmeversorgung Niederrhein GmbH",
        "City": "Dinslaken",
        "Value": "Stammkapital 16.000.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "9638",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fn",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fn"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 22
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "e30d3f30-4050-4d8b-9788-921938e54fe9",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(23)",
        "Id": 23,
        "Title": "Duisburger Versorgungs- und Verkehrsgesellschaft mbH",
        "City": "Duisburg",
        "Value": "Stammkapital 80.402.000,00 DM",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "1171",
        "StNr": "DE 119554655",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dvv",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dvv"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 23
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "b6abf2af-d981-4f93-b166-189f681d8e4b",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(24)",
        "Id": 24,
        "Title": "Duisburg CityCom GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 200.000,00 DM",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "7053",
        "StNr": "DE178629617",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dcc",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dcc"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 24
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1b2ba89e-087d-4123-b5fc-85e8e400fdcc",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(25)",
        "Id": 25,
        "Title": "Gesellschaft für Informationstechnologie Duisburg mbH",
        "City": "Duisburg",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "19232",
        "StNr": "DE254473256",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/duit",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/duit"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 25
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "e17f9ad7-102a-4d43-a0e5-05b0a0ae11c4",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(26)",
        "Id": 26,
        "Title": "octeo MULTISERVICES GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 1.700.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "6422",
        "StNr": "DE164140737",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/octeo",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/octeo"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 26
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "cfe8c5cb-6764-454d-a82b-508f7476f5a6",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(27)",
        "Id": 27,
        "Title": "akuras GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "30418",
        "StNr": "DE275522801",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/akuras",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/akuras"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 27
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "cca3f250-e722-49cf-9f03-748ccb255b9a",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(28)",
        "Id": 28,
        "Title": "Gesellschaft für kommunale Versorgungswirtschaft Nordrhein mbH",
        "City": "Duisburg",
        "Value": "Stammkapital 25.600,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "10479",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/gvn",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/gvn"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 28
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "583bb1ba-4950-4975-bd0b-10ae9f970185",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(29)",
        "Id": 29,
        "Title": "Duisburger Einkaufsgesellschaft mbH",
        "City": "Duisburg",
        "Value": "Stammkapital 27.000,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "26128",
        "StNr": "DE293397774",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/deg",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/deg"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 29
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "3668036e-0a61-41ee-87e7-5cec441e4672",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(30)",
        "Id": 30,
        "Title": "Betriebsverwaltungsgesellschaft Radio Duisburg mbH",
        "City": "Duisburg",
        "Value": "Stammkapital 25.600,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "5041",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/radiodumbh",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/radiodumbh"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 30
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "9a15bee8-0ea1-4134-90ff-226eae92b68d",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(31)",
        "Id": 31,
        "Title": "Betriebsgesellschaft Radio Duisburg mbH & Co. KG",
        "City": "Duisburg",
        "Value": "Kommanditkapital 100.000,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 5984",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/radiodu",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/radiodu"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 31
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "631d979f-c519-40a7-8b9d-6a6d8ed486a6",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(32)",
        "Id": 32,
        "Title": "smartlab Innovationsgesellschaft mbH",
        "City": "Aachen",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "16381",
        "StNr": "DE254473230",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/smartlab",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/smartlab"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 32
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "06a20a8e-9870-4f2c-9a4c-cff25267579e",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(33)",
        "Id": 33,
        "Title": "ID Quadrat Verwaltungsgesellschaft mbH",
        "City": "Düsseldorf",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "83335",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/idtwo",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/idtwo"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 33
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1290c8a1-1ea4-4402-8903-49d6b268ab13",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(34)",
        "Id": 34,
        "Title": "Innovative Immobilien Duisburg Düsseldorf ID Quadrat GmbH & Co. Betriebsgesellschaft KG",
        "City": "Düsseldorf",
        "Value": "Kommanditkapital 1.000,00 €",
        "ParticipationType": "GU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 25268",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/idtwombh",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/idtwombh"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 34
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "7949deef-415e-4c5c-8eba-e0af6bae690d",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(35)",
        "Id": 35,
        "Title": "Zoo Duisburg gGmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 9.313.393,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "32070",
        "StNr": "DE119554495",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/zoo",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/zoo"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 35
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1268833c-6d28-4e47-8f3b-346ff144180d",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(36)",
        "Id": 36,
        "Title": "Duisburger Verkehrsgesellschaft AG",
        "City": "Duisburg",
        "Value": "Grundkapital 14.000.000,00 DM",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "50",
        "StNr": "DE 811271613",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dvg",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dvg"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 36
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "f7d44487-04e9-431a-a621-c21ca1dc38ec",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(37)",
        "Id": 37,
        "Title": "e-clearing.net GmbH",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/eclear",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/eclear"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 37
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "c6b562fc-cd20-47e2-b793-63b5db0f79c3",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(38)",
        "Id": 38,
        "Title": "DataCenter Rhein-Ruhr GmbH",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/datacenter",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/datacenter"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 38
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "86c9c038-a75c-4a11-8912-15f6236871e0",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(39)",
        "Id": 39,
        "Title": "beka GmbH",
        "City": "Köln",
        "Value": "Stammkapital 382.520,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "10190",
        "StNr": "DE 122777321",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/beka",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/beka"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 39
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "08624354-af2d-4e1a-810f-5addb72f682c",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(40)",
        "Id": 40,
        "Title": "Stadtwerke Duisburg Metering GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 50.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "19105",
        "StNr": "DE254132925",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/metering",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/metering"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 40
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1982eb19-c284-420f-8623-b7d34c3bba8e",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(41)",
        "Id": 41,
        "Title": "Duisburg Business & Innovation GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 260.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "4641",
        "StNr": "DE 119 550 686",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/gfw",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/gfw"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 41
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "feb3e8b2-6b09-4118-b06d-1fdd2ebd209a",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(42)",
        "Id": 42,
        "Title": "FN Netz GmbH",
        "City": "Dinslaken",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "33527",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fn-netz",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/fn-netz"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 42
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "7dea3316-1578-426d-9589-afc50946e2d3",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(43)",
        "Id": 43,
        "Title": "Sovorte GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 25.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "35232",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Sovorte",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Sovorte"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 43
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "6e9bd879-b8a2-4828-8c24-ac57459f97da",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(44)",
        "Id": 44,
        "Title": "Duisburger Netzinfrastrukturgesellschaft mbH",
        "City": "Uedem",
        "Value": "Stammkapital 25.000 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRB 34580",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dunig",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/dunig"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 44
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "d8165b0d-9ba7-494f-aadd-bc8a7df5fec5",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(45)",
        "Id": 45,
        "Title": "Windpark Fleetmark II GmbH & Co. KG",
        "City": "Duisburg",
        "Value": "Stammkapital 10.000,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA12669",
        "StNr": "109/5707/1713",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Windpark%20Fleetmark%20II%20GmbH%20%26%20Co.%20KG/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Windpark%20Fleetmark%20II%20GmbH%20%26%20Co.%20KG/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 45
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "6cf7b0af-2183-4a50-b5e5-1a32e29fddbc",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(46)",
        "Id": 46,
        "Title": "Windpark Koßdorf III GmbH & Co. KG",
        "City": "Duisburg",
        "Value": "Stammkapital 10.000,- €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 12666",
        "StNr": "109/5707/1724",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/WindparkKo%C3%9Fdorf/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/WindparkKo%C3%9Fdorf/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 46
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "929533f9-9240-4f17-a238-a4cc62da77fa",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(47)",
        "Id": 47,
        "Title": "Windpark Staustein GmbH & Co. KG",
        "City": "Duisburg",
        "Value": "Stammkapital 10.000,00 €",
        "ParticipationType": "AU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 12668",
        "StNr": "109/5707/1702",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Windpark%20Staustein%20GmbH%20%26%20Co.%20KG/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Windpark%20Staustein%20GmbH%20%26%20Co.%20KG/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 47
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "cc721e61-35e1-4d6c-92ac-72e7cca2feb1",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(48)",
        "Id": 48,
        "Title": "Team Wärmeservice GmbH",
        "City": "Mülheim an der Ruhr",
        "Value": "Stammkapital 25.000,00€",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRB 16000",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Team%20Wärmeservice%20GmbH/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Team%20Wärmeservice%20GmbH/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 48
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "2bcca87c-c028-4612-b9f5-b77ab9bf2d12",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(49)",
        "Id": 49,
        "Title": "Testgesellschaft",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Testgesellschaft/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Testgesellschaft/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 49
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "17218e4a-e32d-44f4-9759-6d33c515660a",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(50)",
        "Id": 50,
        "Title": "VDV eTicket Service GmbH & Co. KG",
        "City": "Köln",
        "Value": "Kommanditkapital 22.500,00 €",
        "ParticipationType": "BU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRA 21866",
        "StNr": "215/5770/0172",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/VDV%20eTicket%20Service%20GmbH%20%26Co.%20KG/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/VDV%20eTicket%20Service%20GmbH%20%26Co.%20KG/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 50
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "3dac95f5-2d0a-4524-a720-d4e8fac06717",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(51)",
        "Id": 51,
        "Title": "New Co GmbH",
        "City": undefined,
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": undefined,
        "FontColor": undefined,
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": undefined,
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 51
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "7c2b5098-0747-4ac0-a639-9e584c1d9a04",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(52)",
        "Id": 52,
        "Title": "Digit4U",
        "City": "Düsseldorf",
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": undefined,
        "FontColor": undefined,
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": false,
        "Inaktiv": true,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Digit4U/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Digit4U/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 52
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "1ecc7bc1-ee17-406c-9dc8-139e47f049f9",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(53)",
        "Id": 53,
        "Title": "hydrogenXpertise GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital: 200.000,00 €",
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "38482",
        "StNr": "109/5800/1269, USt-IdNr. DE450416922",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/hydrogenXpertise%20GmbH/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/hydrogenXpertise%20GmbH/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 53
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "dc8168de-52dc-4777-99e8-65268da8ee65",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(54)",
        "Id": 54,
        "Title": "Solarport Duisburg GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 200.000,00 €",
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "35054",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Solarport%20Duisburg%20GmbH/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Solarport%20Duisburg%20GmbH/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 54
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "bff1b5e9-5483-4f48-aeda-175c6a5288aa",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(55)",
        "Id": 55,
        "Title": "EnerVivo GmbH",
        "City": "Duisburg",
        "Value": "Stammkapital 100.000,00 €",
        "ParticipationType": "VU",
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "38820",
        "StNr": "109/5800/0062",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/EnerVivo%20GmbH/",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/EnerVivo%20GmbH/"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 55
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "a026d0be-e12d-48db-b726-e34525aa831c",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(56)",
        "Id": 56,
        "Title": "Seven2one Informationssysteme GmbH",
        "City": "Karlsruhe",
        "Value": "Stammkapital: 150.000,00 €",
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "109642, Mannheim",
        "StNr": "34417/07079",
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Seven2one",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Seven2one"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 56
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "e212171e-676c-4966-9208-c057929d8e7a",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(57)",
        "Id": 57,
        "Title": "clara energie GmbH",
        "City": "Rosenheim",
        "Value": "Stammkapital: 100.000,00 €",
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": undefined,
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/clara%20energie%20GmbH",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/clara%20energie%20GmbH"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 57
    },
    {
        "odata.type": "SP.Data.CompaniesListItem",
        "odata.id": "c34c1dfc-fd28-47b8-9234-44af146f4812",
        "odata.etag": "\"1\"",
        "odata.editLink": "Web/Lists(guid'60946536-14c0-4503-832b-045bfb399ad7')/Items(58)",
        "Id": 58,
        "Title": "Südnetz GmbH",
        "City": "Duisburg",
        "Value": undefined,
        "ParticipationType": undefined,
        "BackColor": "#ffffff",
        "FontColor": "#003C55",
        "Geschaftsadresse": undefined,
        "Beteiligungsquote": undefined,
        "Ergebnisabfuhrungsvertrag": undefined,
        "StanmkapitalGeschaftsanteile": undefined,
        "Beteiligungsbuchwert": undefined,
        "Unternehmenszweck": undefined,
        "HRBNr": "HRB 39908",
        "StNr": undefined,
        "Ladungsfrist": undefined,
        "AufsichtsratExt": undefined,
        "BeiratExt": undefined,
        "Postfach": undefined,
        "Beteiligung": true,
        "Inaktiv": false,
        "Anfrage_x0020_senden": undefined,
        "Grundungam": undefined,
        "Eintragungam": undefined,
        "LinkUrl": {
            "Description": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Südnetz%20GmbH",
            "Url": "https://spoint.duit.loc/dvv/Beteiligungsmanagement/Südnetz%20GmbH"
        },
        "Logo": undefined,
        "Logo_x0020_Large": undefined,
        "ID": 58
    }
]